Updated script

diff --git a/daemons/easyccg b/daemons/easyccg
--- a/daemons/easyccg
+++ b/daemons/easyccg
@@ -2,16 +2,16 @@
 
 source $(dirname $0)/../scripts/common_source.sh
 
-ESRLPATH="$PROJROOT/ext/easyccg"
+ECCGPATH="$PROJROOT/ext/easyccg"
 PIDFILE=$1
 LOGFILE=$2
 VERSION="0.1.0"
 
-[ -e $ESRLPATH/build/libs/easyccg-${VERSION}-standalone.jar ] || die "$ESRLPATH/build/libs/easyccg-$VERSION-standalone.jar missing, run gradle build"
+[ -e $ECCGPATH/build/libs/easyccg-${VERSION}-standalone.jar ] || die "$ECCGPATH/build/libs/easyccg-$VERSION-standalone.jar missing, run gradle build"
 [ -e $PROJROOT/build/libs/ie-${VERSION}.jar ] || die "$PROJROOT/build/libs/ie-$VERSION.jar missing, run gradle build"
-[ -e $ESRLPATH/model/text/categories ] || die "$ESRLPATH/model/text missing, run scripts/extract_lfs.sh"
+[ -e $ECCGPATH/model/text/categories ] || die "$ECCGPATH/model/text missing, run scripts/extract_lfs.sh"
 
-EXEC="java -jar $ESRLPATH/build/libs/easyccg-$VERSION-standalone.jar --model $ESRLPATH/model/text --daemonize"
+EXEC="java -jar $ECCGPATH/build/libs/easyccg-$VERSION-standalone.jar --model $ECCGPATH/model/text --daemonize"
 if [ "x$PIDFILE" == "x" ]; then
 	$EXEC
 else 
