Change packing from onejar to caspule. Now works with gradle 4.0

diff --git a/daemons/easyccg b/daemons/easyccg
--- a/daemons/easyccg
+++ b/daemons/easyccg
@@ -7,11 +7,11 @@ PIDFILE=$1
 LOGFILE=$2
 VERSION="0.1.0"
 
-[ -e $ECCGPATH/build/libs/easyccg-${VERSION}-standalone.jar ] || die "$ECCGPATH/build/libs/easyccg-$VERSION-standalone.jar missing, run gradle build"
+[ -e $ECCGPATH/build/libs/easyccg-${VERSION}-capsule.jar ] || die "$ECCGPATH/build/libs/easyccg-$VERSION-capsule.jar missing, run gradle build"
 [ -e $PROJROOT/build/libs/ie-${VERSION}.jar ] || die "$PROJROOT/build/libs/ie-$VERSION.jar missing, run gradle build"
 [ -e $ECCGPATH/model/text/categories ] || die "$ECCGPATH/model/text missing, run scripts/extract_lfs.sh"
 
-EXEC="java -jar $ECCGPATH/build/libs/easyccg-$VERSION-standalone.jar --model $ECCGPATH/model/text --daemonize"
+EXEC="java -jar $ECCGPATH/build/libs/easyccg-$VERSION-capsule.jar --model $ECCGPATH/model/text --daemonize"
 if [ "x$PIDFILE" == "x" ]; then
 	$EXEC
 else 
diff --git a/daemons/easysrl b/daemons/easysrl
--- a/daemons/easysrl
+++ b/daemons/easysrl
@@ -9,11 +9,10 @@ shift
 shift
 VERSION="0.1.0"
 
-[ -e $ESRLPATH/build/libs/easysrl-${VERSION}-standalone.jar ] || die "$ESRLPATH/build/libs/easysrl-$VERSION-standalone.jar missing, run gradle build"
-#[ -e $PROJROOT/build/libs/ie-${VERSION}.jar ] || die "$PROJROOT/build/libs/ie-$VERSION.jar missing, run gradle build"
+[ -e $ESRLPATH/build/libs/easysrl-${VERSION}-capsule.jar ] || die "$ESRLPATH/build/libs/easysrl-$VERSION-capsule.jar missing, run gradle build"
 [ -e $ESRLPATH/model/text/categories ] || die "$ESRLPATH/model/text missing, run scripts/extract_lfs.sh"
 
-EXEC="java -jar $ESRLPATH/build/libs/easysrl-$VERSION-standalone.jar --model $ESRLPATH/model/text --daemonize -l 250 $*"
+EXEC="java -jar $ESRLPATH/build/libs/easysrl-$VERSION-capsule.jar --model $ESRLPATH/model/text --daemonize -l 250 $*"
 if [ "x$PIDFILE" == "x" ]; then
 	$EXEC
 else 
